spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: pig-auth
          uri: lb://pig-auth
          predicates:
            - Path=/auth/**
          filters:
            - ValidateCodeGatewayFilter
            - PasswordDecoderFilter
        - id: pig-upms-biz
          uri: lb://pig-upms-biz
          predicates:
            - Path=/admin/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
        - id: pig-codegen
          uri: lb://pig-codegen
          predicates:
            - Path=/gen/**
        - id: pig-quartz
          uri: lb://pig-quartz
          predicates:
            - Path=/job/**
        - id: openapi
          uri: lb://pig-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/$\{path}/v3/api-docs

gateway:
  encode-key: 'thanks,pig4cloud'
  ignore-clients:
    - test
    - client